name: gphase
channels:
  - sfe1ed40
  - anaconda
  - conda-forge
  - bioconda
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_kmp_llvm
  - arpack=3.9.1=nompi_hf03ea27_102
  - bc=1.07.1=h7f98852_0
  - biopython=1.78=py311h5eee18b_0
  - blas=1.0=mkl
  - bottleneck=1.4.2=py311hf4808d0_0
  - brotli-python=1.0.9=py311h6a678d5_9
  - bzip2=1.0.8=h5eee18b_6
  - c-ares=1.19.1=h5eee18b_0
  - ca-certificates=2025.7.9=hbd8a1cb_0
  - certifi=2025.7.9=pyhd8ed1ab_0
  - chromap=0.2.7=hdcf5f25_0
  - contourpy=1.3.1=py311hdb19cb5_0
  - cycler=0.11.0=pyhd3eb1b0_0
  - cyrus-sasl=2.1.28=h52b45da_1
  - dbus=1.13.18=hb2f20db_0
  - expat=2.6.4=h6a678d5_0
  - fontconfig=2.14.1=h55d465d_3
  - fonttools=4.55.3=py311h5eee18b_0
  - freetype=2.12.1=h4a9f257_0
  - glib=2.78.4=h6a678d5_0
  - glib-tools=2.78.4=h6a678d5_0
  - glpk=5.0=h445213a_0
  - gmp=6.3.0=h6a678d5_0
  - htslib=1.21=h5efdd21_0
  - icu=73.1=h6a678d5_0
  - igraph=0.10.15=he44f51b_1
  - intel-openmp=2023.1.0=hdb19cb5_46306
  - jpeg=9e=h5eee18b_3
  - k8=0.2.5=hd03093a_2
  - kiwisolver=1.4.8=py311h6a678d5_0
  - krb5=1.20.1=h143b758_1
  - lcms2=2.16=hb9589c4_0
  - ld_impl_linux-64=2.40=h12ee557_0
  - lerc=4.0.0=h6a678d5_0
  - libabseil=20240116.2=cxx17_h6a678d5_0
  - libblas=3.9.0=1_h86c2bf4_netlib
  - libclang13=14.0.6=default_he11475f_2
  - libcups=2.4.2=h2d74bed_1
  - libcurl=8.11.1=hc9e6f67_0
  - libdeflate=1.22=h5eee18b_0
  - libedit=3.1.20230828=h5eee18b_0
  - libev=4.33=h7f8727e_1
  - libffi=3.4.4=h6a678d5_1
  - libgcc=14.2.0=h77fa898_1
  - libgcc-ng=14.2.0=h69a702a_1
  - libgfortran=14.2.0=h69a702a_1
  - libgfortran-ng=14.2.0=h69a702a_1
  - libgfortran5=14.2.0=hd5240d6_1
  - libglib=2.78.4=hdc74915_0
  - libiconv=1.16=h5eee18b_3
  - liblapack=3.9.0=8_h3b12eaf_netlib
  - libllvm14=14.0.6=hecde1de_4
  - libnghttp2=1.57.0=h2d74bed_0
  - libopenblas=0.3.21=h043d6bf_0
  - libpng=1.6.39=h5eee18b_0
  - libpq=17.2=hdbd6064_0
  - libprotobuf=4.25.3=he621ea3_0
  - libssh2=1.11.1=h251f7ec_0
  - libstdcxx=14.2.0=hc0a3c3a_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - libtiff=4.5.1=hffd6297_1
  - libuuid=1.41.5=h5eee18b_0
  - libwebp-base=1.3.2=h5eee18b_1
  - libxcb=1.15=h7f8727e_0
  - libxkbcommon=1.0.1=h097e994_2
  - libxml2=2.13.5=hfdd30dd_0
  - libxslt=1.1.41=h097e994_0
  - libzlib=1.2.13=h4ab18f5_6
  - llvm-openmp=14.0.6=h9e868ea_0
  - lz4-c=1.9.4=h6a678d5_1
  - matplotlib=3.10.0=py311h38be061_0
  - matplotlib-base=3.10.0=py311hbfdbfaf_0
  - minimap2=2.28=he4a0461_3
  - minizip=4.0.3=hf59b114_0
  - mkl=2023.1.0=h213fc3f_46344
  - mkl-service=2.4.0=py311h5eee18b_2
  - mkl_fft=1.3.11=py311h5eee18b_0
  - mkl_random=1.2.8=py311ha02d727_0
  - mosdepth=0.3.10=h4e814b3_1
  - mysql=8.4.0=h29a9f33_1
  - ncurses=6.4=h6a678d5_0
  - nspr=4.35=h6a678d5_0
  - nss=3.89.1=h6a678d5_0
  - numexpr=2.10.1=py311h3c60e43_0
  - numpy=1.26.4=py311h08b1b3b_0
  - numpy-base=1.26.4=py311hf175353_0
  - openjpeg=2.5.2=he7f1fd0_0
  - openldap=2.6.4=h42fbc30_0
  - openssl=3.5.1=h7b32b05_0
  - packaging=24.2=py311h06a4308_0
  - pandas=2.2.3=py311h6a678d5_0
  - pcre2=10.42=hebb0a14_1
  - pillow=11.1.0=py311hcea889d_0
  - pip=25.0=py311h06a4308_0
  - pyparsing=3.2.0=py311h06a4308_0
  - pyside6=6.7.2=py311hfe62871_0
  - pysam=0.22.1=py311hef863f0_0
  - python=3.11.11=he870216_0
  - python-dateutil=2.9.0post0=py311h06a4308_2
  - python-igraph=0.10.4=py311he621ea3_0
  - python-tzdata=2023.3=pyhd3eb1b0_0
  - python_abi=3.11=2_cp311
  - pytz=2024.1=py311h06a4308_0
  - qtbase=6.7.2=hdaa5aa8_1
  - qtdeclarative=6.7.2=h6a678d5_0
  - qtshadertools=6.7.2=h6a678d5_0
  - qtsvg=6.7.2=he621ea3_0
  - qttools=6.7.2=h80c7b02_0
  - qtwebchannel=6.7.2=h6a678d5_0
  - qtwebengine=6.7.2=hcbda680_0
  - qtwebsockets=6.7.2=h6a678d5_0
  - readline=8.2=h5eee18b_0
  - samtools=1.19.2=h50ea8bc_1
  - seqkit=2.9.0=h9ee0642_0
  - setuptools=75.8.0=py311h06a4308_0
  - six=1.16.0=pyhd3eb1b0_1
  - sortedcontainers=2.4.0=pyhd3eb1b0_0
  - sqlite=3.45.3=h5eee18b_0
  - tbb=2021.8.0=hdb19cb5_0
  - texttable=1.6.4=pyhd3eb1b0_0
  - tk=8.6.14=h39e8969_0
  - tornado=6.4.2=py311h5eee18b_0
  - tzdata=2025a=h04d1e81_0
  - unicodedata2=15.1.0=py311h5eee18b_1
  - wheel=0.45.1=py311h06a4308_0
  - xcb-util-cursor=0.1.4=h5eee18b_0
  - xz=5.4.6=h5eee18b_1
  - yahs=1.2.2=he4a0461_0
  - zlib=1.2.13=h4ab18f5_6
  - zstd=1.5.6=hc292b87_0
  - pip:
      - argcomplete==3.5.3
      - bio-agptools==0.0.3
      - bioframe==0.8.0
      - blinker==1.9.0
      - charset-normalizer==3.4.1
      - click==8.1.8
      - community==1.0.0b1
      - cython==3.1.0
      - dill==0.3.9
      - flask==3.1.0
      - idna==3.10
      - importlib-metadata==8.6.1
      - itsdangerous==2.2.0
      - jinja2==3.1.5
      - joblib==1.4.2
      - kneed==0.8.5
      - markupsafe==3.0.2
      - multiprocess==0.70.17
      - networkit==11.1.post1
      - networkx==3.4.2
      - pairtools==1.1.2
      - pathos==0.3.3
      - patsy==1.0.1
      - portion==2.6.0
      - pox==0.3.5
      - ppft==1.7.6.9
      - pyfaidx==0.8.1.3
      - pyyaml==6.0.2
      - requests==2.32.3
      - scikit-learn==1.6.1
      - scipy==1.15.1
      - screed==1.1.3
      - statsmodels==0.14.4
      - threadpoolctl==3.5.0
      - urllib3==2.3.0
      - werkzeug==3.1.3
      - zipp==3.21.0
